version: "3.8"
services:
  app:
    build: ./docker/php
    volumes:
      - ./laravel:/work:delegated
  web:
    image: nginx:1.18-alpine
    ports:
      - 8080:80
    volumes:
      - ./laravel:/work:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    working_dir: /work
  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql:delegated
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:delegated
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8081:80
volumes:
  db-store:
