version: "3.8"
services:
  app:
    build: ./docker/php
    volumes:
      - ./laravel:/work:delegated
  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./laravel:/work:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    working_dir: /work
  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql:delegated
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:delegated
    environment:
      - MYSQL_DATABASE=laravel_local
      - MYSQL_USER=phper
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
volumes:
  db-store:
